server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user_service
          uri: http://restaurant-user.up.railway.app:8080
          predicates:
            - Path=${app.api-prefix}/user_service/**
          filters:
            - StripPrefix=2

        - id: booking_service
          uri: http://restaurant-booking.up.railway.app:8083
          predicates:
            - Path=${app.api-prefix}/booking_service/**
          filters:
            - StripPrefix=2




