server:
  port: 8083
  servlet:
    context-path: /booking_service

spring:
  data:
    mongodb:
      uri: mongodb://mongo:root@viaduct.proxy.rlwy.net:27487/Restaurant?authSource=admin

app:
  service:
    user: http://restaurant-user.up.railway.app:8080/user_service/user