server:
  port: 8084
  servlet:
    context-path: /invoice_service

spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/Restaurant?authSource=admin

app:
  service:
    menu: http://localhost:8081/menu_service/menu
    table: http://localhost:8082/table_service/table